USE [master]
GO

/****** Object:  Database [EventAB]    Script Date: 2018-08-30 10:40:29 ******/
CREATE DATABASE [EventAB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EventAB', FILENAME = N'C:\Users\Administrator\EventAB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EventAB_log', FILENAME = N'C:\Users\Administrator\EventAB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [EventAB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventAB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventAB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventAB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventAB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventAB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventAB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventAB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EventAB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventAB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventAB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventAB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventAB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventAB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventAB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventAB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventAB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EventAB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventAB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventAB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventAB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventAB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventAB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EventAB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EventAB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EventAB] SET  MULTI_USER 
GO

ALTER DATABASE [EventAB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventAB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EventAB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EventAB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EventAB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EventAB] SET QUERY_STORE = OFF
GO

USE [EventAB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [EventAB] SET  READ_WRITE 
GO

